version: "3.8"

services:
    app:
        image: ghcr.io/sq2cpa/aprs-tnc-web:v1.0.3
        container_name: nextjs_app
        restart: unless-stopped
        networks:
            - app-network
        env_file: .env
        ports:
            - "${PORT:-8000}:8000"

        user: "${UID}:${GID}"
        volumes:
            - ./frames.txt:/app/frames.txt

        environment:
            NODE_ENV: production
            PORT: 8000

            MYSQL_HOST: ${DB_HOST}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASS: ${DB_PASSWORD}
            MYSQL_DB: ${DB_NAME}
        depends_on:
            - mysql_db

    mysql_db:
        image: mysql:8.0
        container_name: mysql_database
        restart: unless-stopped
        networks:
            - app-network

        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

        volumes:
            - mysql-data:/var/lib/mysql

        command: --default-authentication-plugin=mysql_native_password

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
