name: Release and Publish

on:
    workflow_dispatch:
        inputs:
            version:
                required: true
                type: string
                description: "Version"

jobs:
    create_tag:
        name: "Create Git Tag"
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: "Configure Git user"
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"

            - name: "Create and push tag"
              run: |
                  git tag -a ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }}"
                  git push origin ${{ github.event.inputs.version }}

    publish:
        name: "Build and Publish Docker Image"
        runs-on: ubuntu-latest
        needs: create_tag
        permissions:
            contents: read
            packages: write
        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.version }}

            - name: "Log into GitHub Container Registry"
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: "Build and tag Docker image"
              run: docker build -t ghcr.io/${{ github.repository }}:${{ github.event.inputs.version }} .

            - name: "Publish Docker image"
              run: docker push ghcr.io/${{ github.repository }}:${{ github.event.inputs.version }}
